# Step 1: Use an official Maven image to build the application
FROM maven:3.9.1-eclipse-temurin-17 AS build

# Set the working directory for the build stage
WORKDIR /app

# Copy the pom.xml and install dependencies (without copying the full source code yet)
COPY pom.xml ./

# Download the dependencies
RUN mvn clean install -DskipTests

# Step 2: Copy the source code into the container
COPY src ./src

# Step 3: Build the application using the Spring Boot Maven plugin
RUN mvn package -DskipTests

# List the contents of the target directory to verify the build output
RUN ls -l /app/target/

# Step 4: Create a new image from the OpenJDK image for running the application
FROM eclipse-temurin:17-jre-alpine

# Set the working directory for running the application
WORKDIR /app

# Explicitly copy the JAR file generated by Maven to the final image
COPY --from=build /app/target/*.jar /app/app.jar

# Set permissions for the app folder to ensure it is writable
RUN chmod -R 755 /app

# Expose the port that your application will listen on (default Spring Boot port is 8080)
EXPOSE 8080

# Command to run the application
ENTRYPOINT ["java", "-jar", "/app/app.jar"]